name: "Home Assistant Professional"
description: "Enables home assistant to be usable in batch"
slug: "hapro"
version: "0.0.1"
url: "https://github.com/bitfox-git/hapro-addon"
init: false
host_network: true
homeassistant_api: true
hassio_api: true
arch:
  - aarch64
  - amd64
map:
  - homeassistant_config:ro
