name: "hapro"
description: "Professional manager for multiple HA installations."
slug: "hapro"
version: "v1.0-alpha11.3"
image: ghcr.io/bitfox-git/hapro-addon-{arch}
url: "https://github.com/bitfox-git/hapro-addon/tree/main/hapro"
init: false
host_network: true
homeassistant_api: true
hassio_api: true
hassio_role: "manager"
arch:
  - aarch64
  - amd64
map:
  - homeassistant_config:rw
  - backup:rw
options:
  uuid: str